*&---------------------------------------------------------------------*
*&  Include           ZFI_SUBIDA_RETENCIONES_TOP
*&---------------------------------------------------------------------*
TABLES : bkpf.
TYPE-POOLS : slis.

CONSTANTS : c_j TYPE c VALUE 'J',
            c_k TYPE c VALUE 'K',
            c_h TYPE c VALUE 'H',
            c_c TYPE c VALUE 'C',
            c_x TYPE c VALUE 'X'.

DATA: BEGIN OF ti_entrada OCCURS 0,
         blart TYPE bkpf-blart,
         xblnr TYPE bkpf-xblnr,
         stcd1 TYPE lfa1-stcd1,
         budat TYPE bkpf-budat,
         mandt TYPE with_item-mandt,
         bukrs TYPE  with_item-bukrs,
         belnr TYPE  with_item-belnr,
         gjahr TYPE  with_item-gjahr,
         buzei TYPE  with_item-buzei,
         witht TYPE  with_item-witht,
         wt_withcd TYPE  c LENGTH 16,
         wt_qsshh  TYPE  c LENGTH 16,
         wt_qsshb  TYPE  c LENGTH 16,
         wt_qssh2  TYPE  c LENGTH 16,
         wt_qssh3  TYPE  c LENGTH 16,
         wt_basman TYPE  c LENGTH 16,
         wt_qsshhc TYPE  c LENGTH 16,
         wt_qsshbc TYPE  c LENGTH 16,
         wt_qssh2c TYPE  c LENGTH 16,
         wt_qssh3c TYPE  c LENGTH 16,
         wt_qbshh  TYPE  c LENGTH 16,
         wt_qbshb  TYPE  c LENGTH 16 ,
         wt_qbsh2  TYPE  c LENGTH 16 ,
         wt_qbsh3  TYPE  c LENGTH 16 ,
         wt_amnman TYPE  c LENGTH 16 ,
         wt_qbshha TYPE  c LENGTH 16 ,
         wt_qbshhb TYPE  c LENGTH 16 ,
         wt_stat   TYPE  wt_stat ,
         wt_qsfhh  TYPE  c LENGTH 16 ,
         wt_qsfhb  TYPE  c LENGTH 16 ,
         wt_qsfh2  TYPE  c LENGTH 16 ,
         wt_qsfh3  TYPE  c LENGTH 16 ,
         wt_wtexmn TYPE  wt_exnr ,
         koart     TYPE  koart ,
         wt_acco   TYPE  wt_acno ,
         hkont     TYPE  hkont ,
         hkont_opp TYPE  hkont ,
         qsrec TYPE  wt_qsrec  ,
         augbl TYPE  augbl ,
         augdt TYPE  augdt ,
         wt_qszrt  TYPE  c LENGTH 16 ,
         wt_wdmbtr TYPE  c LENGTH 16 ,
         wt_wwrbtr TYPE  c LENGTH 16 ,
         wt_wdmbt2 TYPE  c LENGTH 16 ,
         wt_wdmbt3 TYPE  c LENGTH 16 ,
         text15  TYPE  text15  ,
         wt_qbuihh TYPE  c LENGTH 16 ,
         wt_qbuihb TYPE  c LENGTH 16 ,
         wt_qbuih2 TYPE  c LENGTH 16 ,
         wt_qbuih3 TYPE  c LENGTH 16 ,
         wt_accbs  TYPE  c LENGTH 16 ,
         wt_accwt  TYPE  c LENGTH 16 ,
         wt_accwta TYPE  c LENGTH 16 ,
         wt_accwtha      TYPE  c LENGTH 16 ,
         wt_accbs1       TYPE  c LENGTH 16 ,
         wt_accwt1       TYPE  c LENGTH 16 ,
         wt_accwta1      TYPE  c LENGTH 16 ,
         wt_accwtha1     TYPE  c LENGTH 16 ,
         wt_accbs2       TYPE  c LENGTH 16 ,
         wt_accwt2       TYPE  c LENGTH 16 ,
         wt_accwta2      TYPE  c LENGTH 16 ,
         wt_accwtha2     TYPE  c LENGTH 16 ,
         qsatz           TYPE  c LENGTH 16 ,
         wt_slfwtpd      TYPE  wt_slfwtpd  ,
         wt_gruwtpd      TYPE  wt_gruwtpd  ,
         wt_opowtpd      TYPE  wt_opowtpd  ,
         wt_givenpd      TYPE  wt_givenpd  ,
         ctnumber        TYPE  ctnumber  ,
         wt_downc        TYPE  wt_downc  ,
         wt_resitem      TYPE  wt_resitem  ,
         ctissuedate     TYPE  ctissuedate ,
         j_1bwhtcollcode TYPE  j_1bwhtcoll ,
         j_1bwhtrate   TYPE  c LENGTH 16 ,
         j_1bwht_bs    TYPE  c LENGTH 16 ,
         j_1bwhtaccbs  TYPE  c LENGTH 16 ,
         j_1bwhtaccbs1 TYPE  c LENGTH 16 ,
         j_1bwhtaccbs2 TYPE  c LENGTH 16 ,
         j_1iintchln TYPE  j_1iintchln ,
         j_1iintchdt TYPE  j_1iintchdt ,
         j_1iewtrec  TYPE  j_1iewtrec  ,
         j_1ibuzei   TYPE  buzei ,
         j_1icertdt  TYPE  j_1icertdt  ,
         j_1iclramt  TYPE  c LENGTH 16 ,
         j_1irebzg   TYPE  rebzg ,
         j_1isuramt  TYPE  c LENGTH 16 ,
END OF ti_entrada.

  DATA: ti_with_item TYPE TABLE OF with_item,
        wa_with_item TYPE with_item.

* Catálogo de campos: contiene la descripción de los campos de salida
DATA: gt_fieldcat TYPE slis_t_fieldcat_alv ,
      gt_sort     TYPE slis_t_sortinfo_alv WITH HEADER LINE,
* Especificaciones de la disposición de la lista: descripción de la
* estructura de salida
      gs_layout            TYPE slis_layout_alv,
      gt_list_top_of_page  TYPE slis_t_listheader,
      gt_events            TYPE slis_t_event,
*     gt_sort              type slis_t_sortinfo_alv,
      ls_vari              TYPE disvariant,
      g_repid              LIKE sy-repid.
