*&---------------------------------------------------------------------*
*&  Include           ZFI_ACTUALIZA_REGUH_REGUP_TOP
*&---------------------------------------------------------------------*

TYPE-POOLS: slis.

DATA: ti_reguh TYPE TABLE OF reguh,
      wa_reguh TYPE reguh,
      ti_regup TYPE TABLE OF regup,
      wa_regup TYPE regup.


TYPES: BEGIN OF t_aux_reguh,
mandt TYPE  mandt ,
laufd TYPE  c LENGTH 10, "laufd ,
laufi TYPE  laufi ,
xvorl TYPE  xvorl ,
zbukr TYPE  dzbukr  ,
lifnr TYPE  lifnr ,
kunnr TYPE  kunnr ,
empfg TYPE  empfg ,
vblnr TYPE  vblnr ,
avisg TYPE  avisg ,
waers TYPE  waers ,
srtgb TYPE  gsber ,
anred TYPE  anred ,
name1 TYPE  name1_gp  ,
name2 TYPE  name2_gp  ,
name3 TYPE  name3_gp  ,
name4 TYPE  name4_gp  ,
pstlz TYPE  pstlz ,
ort01 TYPE  ort01_gp  ,
stras TYPE  stras_gp  ,
pfach TYPE  pfach ,
land1 TYPE  land1 ,
stcd1 TYPE  stcd1 ,
wevwv TYPE  wevwv ,
zanre TYPE  dzanre  ,
znme1 TYPE  dznme1  ,
znme2 TYPE  dznme1  ,
znme3 TYPE  dznme1  ,
znme4 TYPE  dznme1  ,
zpstl TYPE  dzpstl  ,
zort1 TYPE  dzort1  ,
zstra TYPE  dzstra  ,
zpfac TYPE  dzpfac  ,
zland TYPE  dzland  ,
zregi TYPE  dzregi  ,
zbnks TYPE  dzbnks  ,
zbnkn TYPE  dzbnkn  ,
zbnkl TYPE  dzbnkl  ,
zbkon TYPE  dzbkon  ,
zbvty TYPE  dzbvty  ,
zswif TYPE  swift ,
xezer TYPE  xezer ,
zspra TYPE  dzspra  ,
zaldt TYPE  c LENGTH 10, "zaldt
rzawe TYPE  rzawe ,
rumsk TYPE  rumsk ,
rzums TYPE  rzums ,
hktid TYPE  hktid ,
hbkid TYPE  hbkid ,
hktiw TYPE  hktiw ,
hbkiw TYPE  hbkiw ,
bvtyp TYPE  bvtyp ,
ubkon TYPE  ubkon ,
ubknt TYPE  ubknt ,
ubnks TYPE  banks ,
ubnkl TYPE  ubnkl ,
ubhkt TYPE  ubhkt ,
valut TYPE  c LENGTH 10, "valut ,
crval TYPE  prq_crval ,
anfae TYPE  c LENGTH 10, "anfae ,
wefae TYPE  c LENGTH 10, "wefae ,
rbetr TYPE  c LENGTH 20, "rbetr ,
rskon TYPE  rskon ,
rwbtr TYPE  c LENGTH 20, "rwbtr ,
rwskt TYPE  c LENGTH 20, "rwskt ,
rspe1 TYPE  c LENGTH 20, "spes1 ,
rspe2 TYPE  c LENGTH 20, "spes2 ,
rpost TYPE  rpost ,
rtext TYPE  rtext_d ,
rspm1 TYPE  c LENGTH 20, "spem1 ,
rspm2 TYPE  c LENGTH 20, "spem2 ,
wehmx TYPE  c LENGTH 20, "wehmx ,
wefmx TYPE  c LENGTH 20, "wefmx ,
wehrs TYPE  c LENGTH 20, "wehrs ,
wefrs TYPE  c LENGTH 20, "wefrs ,
weamx TYPE  weamx ,
busab TYPE  busab ,
eikto TYPE  eikto ,
xinve TYPE  xinve ,
wdate TYPE  wdate ,
xaend TYPE  xaend_regu  ,
zlspr TYPE  dzlspr  ,
dtaws TYPE  dtaws ,
dtams TYPE  dtams ,
kursf TYPE  kursf ,
abwae TYPE  abwae ,
skvhw TYPE  c LENGTH 20, "skvhw ,
skvfw TYPE  c LENGTH 20, "skvfw ,
dskvh TYPE  c LENGTH 20, "dskvh ,
zpst2 TYPE  dzpst2  ,
paygr TYPE  paygr ,
zbnky TYPE  dzbnky  ,
ubnky TYPE  ubnky ,
pstl2 TYPE  pstl2 ,
absbu TYPE  absbu ,
rbet2 TYPE  c LENGTH 20, "rbet2 ,
rbet3 TYPE  c LENGTH 20, "rbet3 ,
rsko2 TYPE  c LENGTH 20, "rsko2 ,
rsko3 TYPE  c LENGTH 20, "rsko3 ,
kurs2 TYPE  kurs2 ,
kurs3 TYPE  kurs3 ,
bkref TYPE  bkref ,
uzawe TYPE  uzawe ,
zort2 TYPE  ort02_z ,
ztlfx TYPE  telfx_z ,
xsiwe TYPE  xsiwe ,
zpfor TYPE  pfort_z ,
pernr TYPE  pernr_d ,
seqnr TYPE  seqc5 ,
btznr TYPE  btznr ,
ausfd TYPE  c LENGTH 10 ,
ediav TYPE  ediav ,
idoc_num_avis TYPE  edi_docnum  ,
edibn TYPE  edibn ,
idoc_num  TYPE  edi_docnum  ,
ztelf TYPE  telfn_z ,
ztelx TYPE  telex_z ,
koinh TYPE  koinh_fi  ,
dtws1 TYPE  dtat16  ,
dtws2 TYPE  dtat17  ,
dtws3 TYPE  reguh-dtws3  ,
dtws4 TYPE  dtat19  ,
zstc1 TYPE  stcd1_z ,
kidno TYPE  kidno ,
pyord TYPE  pyord ,
regio TYPE  regio ,
text  TYPE  text  ,
btyp1 TYPE  bntyp ,
bnks1 TYPE  banks ,
bnkl1 TYPE  bankk ,
bnkn1 TYPE  bankn ,
bkon1 TYPE  bkont ,
bkrf1 TYPE  bkref ,
btyp2 TYPE  bntyp ,
bnks2 TYPE  banks ,
bnkl2 TYPE  bankk ,
bnkn2 TYPE  bankn ,
bkon2 TYPE  bkont ,
bkrf2 TYPE  bkref ,
btyp3 TYPE  bntyp ,
bnks3 TYPE  banks ,
bnkl3 TYPE  bankk ,
bnkn3 TYPE  bankn ,
bkon3 TYPE  bkont ,
bkrf3 TYPE  bkref ,
saknr TYPE  saknr ,
hkont TYPE  hkont ,
alebn TYPE  alebn ,
xkdfb TYPE  xkdfb_042e  ,
srtbp TYPE  bupla ,
fpm_key TYPE  fpm_key ,
grpno TYPE  grpno_fpm ,
srtf1 TYPE  srtf1n_fpm  ,
srtf2 TYPE  srtf2n_fpm  ,
srtf3 TYPE  srtf1n_fpm  ,
xcorr TYPE  xcorr_fpm ,
xavis TYPE  xavis_fpm ,
xcopm TYPE  xcopm_fpm ,
dorigin TYPE  fibl_dorigin  ,
rfttrn  TYPE  rfttrn_bf ,
zadnr TYPE  adrnr_z ,
adrnr TYPE  ad_addrnum  ,
ziban TYPE  dziban  ,
mguid TYPE  sepa_mguid  ,
fm_status TYPE  fm_pay_sta  ,
file_nbr  TYPE  fmfg_file_no  ,
identif_pago  TYPE  char15  ,
fecha_envio TYPE c LENGTH 10, "TYPE  datum ,
usuario_envio TYPE  uname ,
ind_pago  TYPE  char01  ,
fecha_pago  TYPE c LENGTH 10, "TYPE  datum ,
ind_devuelto  TYPE  char01  ,
fecha_devuelto TYPE c LENGTH 10, "TYPE  datum ,
ind_rechazo TYPE  char01  ,
fecha_rechazo TYPE c LENGTH 10, "TYPE  datum ,
belnr_dev TYPE  belnr_d ,
gjahr_dev TYPE  gjahr ,
ind_custodia  TYPE  char01  ,
fecha_custodia  TYPE c LENGTH 10, "TYPE  datum ,
motivo_rechazo  TYPE  descr40 ,
ind_entregado TYPE  char01  ,
fecha_entregado TYPE c LENGTH 10, "TYPE  datum ,
ind_rescatado TYPE  char01  ,
fecha_rescatado TYPE c LENGTH 10, "TYPE  datum ,
END OF t_aux_reguh.

DATA: ti_aux_reguh TYPE TABLE OF t_aux_reguh,
      wa_aux_reguh TYPE t_aux_reguh.


TYPES: BEGIN OF t_regup,
  mandt TYPE  mandt ,
laufd TYPE  c LENGTH 10,"laufd ,
laufi TYPE  laufi ,
xvorl TYPE  xvorl ,
zbukr TYPE  dzbukr  ,
lifnr TYPE  lifnr ,
kunnr TYPE  kunnr ,
empfg TYPE  empfg ,
vblnr TYPE  vblnr ,
bukrs TYPE  bukrs ,
belnr TYPE  belnr_d ,
gjahr TYPE  gjahr ,
buzei TYPE  buzei ,
filkd TYPE  filkd ,
zlsch TYPE  dzlsch  ,
waers TYPE  waers ,
hbkid TYPE  hbkid ,
bvtyp TYPE  bvtyp ,
poken TYPE  poken ,
xblnr TYPE  xblnr1  ,
blart TYPE  blart ,
budat TYPE  c LENGTH 10,"budat ,
bldat TYPE  c LENGTH 10,"bldat ,
koart TYPE  koart ,
bschl TYPE  bschl ,
hkont TYPE  hkont ,
saknr TYPE  saknr ,
umskz TYPE  umskz ,
umsks TYPE  umsks ,
zumsk TYPE  dzumsk  ,
shkzg TYPE  shkzg ,
dmbtr TYPE  c LENGTH 20, "dmbtr ,
wrbtr TYPE  c LENGTH 20, "wrbtr ,
bdiff TYPE  bdiff ,
gsber TYPE  gsber ,
mwskz TYPE  mwskz ,
mwsts TYPE  c LENGTH 20, "mwsts ,
wmwst TYPE  c LENGTH 20, "wmwst ,
mwsk1 TYPE  mwskx ,
dmbt1 TYPE  c LENGTH 20, "dmbtx ,
wrbt1 TYPE  c LENGTH 20, "wrbtx ,
mwsk2 TYPE  mwskx ,
dmbt2 TYPE  c LENGTH 20, "dmbtx ,
wrbt2 TYPE  c LENGTH 20, "wrbtx ,
mwsk3 TYPE  mwskx ,
dmbt3 TYPE  c LENGTH 20, "dmbtx ,
wrbt3 TYPE  c LENGTH 20, "wrbtx ,
sgtxt TYPE  sgtxt ,
zfbdt TYPE  c LENGTH 10,"dzfbdt  ,
zterm TYPE  dzterm  ,
zbd1t TYPE  dzbd1t  ,
zbd2t TYPE  dzbd2t  ,
zbd3t TYPE  dzbd3t  ,
zbd1p TYPE  dzbd1p  ,
zbd2p TYPE  dzbd2p  ,
skfbt TYPE  skfbt ,
sknto TYPE  sknto ,
wskto TYPE  wskto ,
zbfix TYPE  dzbfix  ,
zlspr TYPE  dzlspr  ,
splev TYPE  splev ,
xrebz TYPE  xrebz ,
zollt TYPE  dzollt  ,
zolld TYPE  dzolld  ,
lzbkz TYPE  lzbkz ,
landl TYPE  landl ,
diekz TYPE  diekz ,
qsskz TYPE  qsskz ,
qsshb TYPE  c LENGTH 20, "qsshb ,
qbshb TYPE  c LENGTH 20, "qbshb ,
qbshh TYPE  c LENGTH 20, "qbshh ,
esrnr TYPE  esrnr ,
esrre TYPE  esrre ,
esrpz TYPE  esrpz ,
zbdxt TYPE  dzbdxt  ,
zbdxp TYPE  dzbdxp  ,
mshbt TYPE  c LENGTH 20, "mshbt ,
msfbt TYPE  c LENGTH 20, "msfbt ,
projn TYPE  projn ,
aufnr TYPE  aufnr ,
anln1 TYPE  anln1 ,
anln2 TYPE  anln2 ,
ebeln TYPE  ebeln ,
ebelp TYPE  ebelp ,
xanet TYPE  xanet ,
xnetb TYPE  xnetb ,
xnach TYPE  xnach ,
zwels TYPE  dzwels  ,
vbund TYPE  rassc ,
stceg TYPE  stceg ,
egbld TYPE  egbld ,
eglld TYPE  eglld ,
qsznr TYPE  qsznr ,
bdif2 TYPE  bdif2 ,
dskvh TYPE  dskvh ,
pokla TYPE  pokla ,
fipos TYPE  fipos ,
projk TYPE  ps_psp_pnr  ,
nplnr TYPE  nplnr ,
aufpl TYPE  co_aufpl  ,
aplzl TYPE  cim_count ,
xegdr TYPE  xegdr ,
bdif3 TYPE  bdif3 ,
dmbe2 TYPE  c LENGTH 20,                                    "dmbe2 ,
dmbe3 TYPE  c LENGTH 20,                                    "dmbe3 ,
mwst2 TYPE  c LENGTH 20,                                    "mwst2 ,
sknt2 TYPE  c LENGTH 20,                                    "sknt2 ,
sknt3 TYPE  c LENGTH 20,                                    "sknt3 ,
qbsh2 TYPE  c LENGTH 20,                                    "qbsh2 ,
qbsh3 TYPE  c LENGTH 20,                                    "qbsh3 ,
dmb21 TYPE  c LENGTH 20,                                    "dmb2x ,
dmb22 TYPE  c LENGTH 20,                                    "dmb2x ,
dmb23 TYPE  c LENGTH 20,                                    "dmb2x ,
dmb31 TYPE  c LENGTH 20,                                    "dmb3x ,
dmb32 TYPE  c LENGTH 20,                                    "dmb3x ,
dmb33 TYPE  c LENGTH 20,                                    "dmb3x ,
uzawe TYPE  uzawe ,
mwst3 TYPE  c LENGTH 20,                                    "mwst3 ,
zuonr TYPE  dzuonr  ,
oskto TYPE  sknto ,
vertn TYPE  ranl  ,
imkey TYPE  imkey ,
rebzt TYPE  rebzt ,
rebzg TYPE  rebzg ,
rebzj TYPE  rebzj ,
rebzz TYPE  rebzz ,
kostl TYPE  kostl ,
xinve TYPE  xinve ,
vbel2 TYPE  vbeln_va  ,
vpos2 TYPE  num06 ,
zekkn TYPE  dzekkn  ,
posn2 TYPE  posnr_va  ,
eten2 TYPE  etenr ,
fistl TYPE  fistl ,
geber TYPE  bp_geber  ,
dabrz TYPE  dabrbez ,
kkber TYPE  kkber ,
empfb TYPE  empfb ,
prctr TYPE  prctr ,
xref1 TYPE  xref1 ,
xref2 TYPE  xref2 ,
xref3 TYPE  xref3 ,
zinkz TYPE  dzinkz  ,
dtws1 TYPE  dtat16  ,
dtws2 TYPE  dtat17  ,
dtws3 TYPE  dtat18  ,
dtws4 TYPE  dtat19  ,
mansp TYPE  mansp ,
kidno TYPE  kidno ,
xcpdd TYPE  xcpdd ,
vertt TYPE  rantyp  ,
vbewa TYPE  sbewart ,
agzei TYPE  agzei ,
pswsl TYPE  pswsl ,
pswbt TYPE  c LENGTH 20, "pswbt ,
psskt TYPE  c LENGTH 20, "psskt ,
xpyam TYPE  xpyam ,
gdiff TYPE  c LENGTH 20, "gdiff ,
gdif2 TYPE  c LENGTH 20, "gdiff ,
gdif3 TYPE  c LENGTH 20, "gdiff ,
bupla TYPE  bupla ,
secco TYPE  secco ,
xsaen TYPE  xsaen ,
kblnr TYPE  kblnr_fi  ,
kblpos  TYPE  kblpos  ,
keyno TYPE  prq_keyno ,
pamtf TYPE  prq_amtfc ,
origin  TYPE  fibl_origin ,
penlc1  TYPE  c LENGTH 20, "penalty1  ,
penlc2  TYPE  c LENGTH 20, "penalty2  ,
penlc3  TYPE  c LENGTH 20, "penalty3  ,
penfc TYPE  c LENGTH 20, "penalty ,
pendays TYPE  pdays ,
pprct TYPE  pprctr  ,
grant_nbr TYPE  gm_grant_nbr  ,
fkber TYPE  fkber ,
sname1  TYPE  name1_gp  ,
sort01  TYPE  ort01_gp  ,
sland1  TYPE  land1_gp  ,
samnr TYPE  samnr ,
maber TYPE  maber ,
       END OF t_regup.

DATA: ti_aux_regup TYPE TABLE OF t_regup,
      wa_aux_regup TYPE t_regup.

* Catálogo de campos: contiene la descripción de los campos de salida
DATA: gt_fieldcat TYPE slis_t_fieldcat_alv ,
      gt_sort     TYPE slis_t_sortinfo_alv WITH HEADER LINE,
* Especificaciones de la disposición de la lista: descripción de la
* estructura de salida
      gs_layout            TYPE slis_layout_alv,
      gt_list_top_of_page  TYPE slis_t_listheader,
      gt_events            TYPE slis_t_event,
      ls_vari              TYPE disvariant,
      g_repid              LIKE sy-repid.
