
* BEGIN. 08-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT single *
*  into CORRESPONDING FIELDS Of wa_ekko
*  from ekko
*  where ebeln eq v_ebeln.
*
* NEW CODE
SELECT *
UP TO 1 ROWS 
  into CORRESPONDING FIELDS Of wa_ekko
  from ekko
  where ebeln eq v_ebeln ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 08-07-2026 - ATC - ATC-01

* BEGIN. 08-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE *
*INTO CORRESPONDING FIELDS OF wa_lfa1
*FROM lfa1
*WHERE lifnr EQ wa_ekko-lifnr.
*
* NEW CODE
SELECT *
UP TO 1 ROWS 
INTO CORRESPONDING FIELDS OF wa_lfa1
FROM lfa1
WHERE lifnr EQ wa_ekko-lifnr ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 08-07-2026 - ATC - ATC-01

* BEGIN. 08-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE *
*INTO CORRESPONDING FIELDS OF wa_KNVK
*FROM KNVK
*WHERE lifnr EQ wa_ekko-lifnr.
*
* NEW CODE
SELECT *
UP TO 1 ROWS 
INTO CORRESPONDING FIELDS OF wa_KNVK
FROM KNVK
WHERE lifnr EQ wa_ekko-lifnr ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 08-07-2026 - ATC - ATC-01

* BEGIN. 08-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE *
*INTO CORRESPONDING FIELDS OF wa_LFM1
*FROM LFM1
*WHERE lifnr EQ wa_ekko-lifnr.
*
* NEW CODE
SELECT *
UP TO 1 ROWS 
INTO CORRESPONDING FIELDS OF wa_LFM1
FROM LFM1
WHERE lifnr EQ wa_ekko-lifnr ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 08-07-2026 - ATC - ATC-01

* BEGIN. 08-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE *
*INTO CORRESPONDING FIELDS OF wa_T052
*FROM T052
*WHERE ZTERM EQ wa_lfm1-ZTERM.
*
* NEW CODE
SELECT *
UP TO 1 ROWS 
INTO CORRESPONDING FIELDS OF wa_T052
FROM T052
WHERE ZTERM EQ wa_lfm1-ZTERM ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 08-07-2026 - ATC - ATC-01






















