CLEAR GV_MAKTX.
* BEGIN. 08-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE MAKTX FROM MAKT INTO GV_MAKTX
*  WHERE MATNR = GS_MSEG-MATNR
*    AND SPRAS = 'S'.
*
* NEW CODE
SELECT MAKTX
UP TO 1 ROWS  FROM MAKT INTO GV_MAKTX
  WHERE MATNR = GS_MSEG-MATNR
    AND SPRAS = 'S' ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 08-07-2026 - ATC - ATC-01

*SELECT SINGLE zzdescr FROM zunid_prod INTO gv_hd_und_desc
*  WHERE bukrs = is_mseg-bukrs
*    AND zzcod_unidad = is_mseg-zzunid_pro.

* BEGIN. 08-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE BDTER BDMNG MEINS FROM RESB
*    INTO (GV_HD_BDTER, GV_BDMNG, GV_MEINS)
*      WHERE RSNUM = GS_MSEG-RSNUM
*        AND RSPOS = GS_MSEG-RSPOS
*        AND RSART = GS_MSEG-RSART.
*
* NEW CODE
  SELECT BDTER BDMNG MEINS
  UP TO 1 ROWS  FROM RESB
    INTO (GV_HD_BDTER, GV_BDMNG, GV_MEINS)
      WHERE RSNUM = GS_MSEG-RSNUM
        AND RSPOS = GS_MSEG-RSPOS
        AND RSART = GS_MSEG-RSART ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 08-07-2026 - ATC - ATC-01




















